### ISSUE TITLE
issue when using module on Windows server 2016 KO - Win10 OK

### ISSUE THREAD

**Issue by emanent** [treestryder/powershell_module_workdayapi#10]
Hi all 
i have to run a workday powershell script on a ws2016.
i've developed a very easy working script on win 10 who do the job (browse wokday directory)
Import-Module WorkdayApi
Set-WorkdayCredential ...
Set-WorkdayEndpoint  ...
 Get-WorkdayWorker -IncludePersonal | ForEach-Object {     $worker = $_  }

when copying the script to ws2016 with same executionpolicy/same powershell version and admin rights for powershell + your module version 2.2.2 dully installed (verified by get-module) i get the following error generated by the script and especially  Get-WorkdayWorker
Impossible d’appeler une méthode dans une expression Null.
Au caractère C:\Program Files\WindowsPowerShell\Modules\WorkdayApi\scripts\Invoke-WorkdayRequest.ps1:117 : 3
+         $reader = New-Object System.IO.StreamReader -ArgumentList $_. ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

do you know where it can come from ?
looks like security is OK (same return on ws2016/win10) when reaching directly the endpoints URLs..
both OS in french version.. 
by the way merry christmas to everybody !
emmanuel

**Comment by emanent** [comment]
Hello i just found out !
just had to add 
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
to my script before to set my credentials and my script is now working fine on windows server 2016 !
if it can help somebody
it is linked to a recent evolution of workday API
it's just weird that the behavior is not the same in win10 / windows server 2016 by default.
Regards
Emmanuel

**Comment by treestryder** [comment]
Sorry, I only now saw this.

You figured out what one of the problems was and found an excellent workaround. I need to add this to the [Wiki page about Workday no longer supporting SSL and TLS v1.0](
https://github.com/treestryder/powershell_module_workdayapi/wiki/SSL-and-TLS-1.0). 

Another problem would be the poor error handling, when Workday denied the connection. I am reopening this issue as a reminder to see if this type of error could be better handled..

**Comment by treestryder** [comment]
The error handling has been somewhat improved.
