### ISSUE TITLE
"the return of issue" when using module on Windows server 2016 KO - Win10 OK

### ISSUE THREAD

**Issue by emanent** [treestryder/powershell_module_workdayapi#13]
Hello all and happy new year to everybody !

Treestryder, thank's for having worked on my previous issue, i've downloaded your improvements (note that there is a minor issue in Install.ps1 where you have to change '.\source\scripts\', to '.\source\public\',) if you want the install script to work
meanwhile i have a much major issue my bug is back !
all was fine on win10 and ws2016 with my enforcing "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;" until... the exact end of year...
since 01/01 my script has stoped working on windows server ; first we thought of an issue with passwords and had new password emitted but without success.
but when i went back to my win10 workstation, it was working fine !!

there is another curious fact .
when i set a wrong password on win 10
the following code 
write $worker.Success
write $worker.Message
returns 
False
SOAP-ENV:Client.authentificationError: invalid username or password
(and returns is OK if password is good )

wether i have a false password or the right one on windows server 2016 (since 01/01/2020)
the exact same script returns a full xml error message 
False
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Access Denied (authentication_failed)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials c
an be verified.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.<br><br>Your request was categorized by Blue Coat Web Filter as 'Business/Econom
y'. <br>If you wish to question or dispute this result, please click <a href="http://sitereview.bluecoat.com/sitereview.jsp?referr
er=136&url=tcp://wd3-impl-services1.workday.com:443/">here</a>.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>

**Comment by emanent** [comment]
hello, i've got some aditional news.
i've tried to use an other windows server 2016 hosted in a VM on my win10.
when  i try to run the script after having booted win 10 and the VM 
if i start with the VM windows server 2016 i got error (in french sorry) 
La demande a été abandonnée : Impossible de créer un canal sécurisé SSL/TLS.

if i go back to the win10 host then i'm able to browse the workday directory
and then i go back to the VM windows server 2016 and i can also browse the workday directory !

looks like the win10 is able to set the SSL canal that can be used by the VM hosted whereas the windows server 2016 can't instantiate the SSL canal.. interesting...

**Comment by emanent** [comment]
in my last comment i had comented the following line in the ws2016 code
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
will try later with tls12 enforced and start with the VM..

**Comment by treestryder** [comment]
> For assistance, contact your network support team.
> Your request was categorized by Blue Coat Web Filter as 'Business/Econom y'.
> If you wish to question or dispute this result, please click here. 

I would share this thread with your "network support team". It looks to me, as if though their web proxy is set to block business sites. In this case "wd3-impl-services1.workday.com".


Also, I am not sure if you have seen this, however there is a way to force .Net to use the more recent encryption protocols. I believe this is the default (or better) on Windows 10 and 2016. Thus, forcing the session to use TLS 1.2 (with that line of Powershell) might actually lower your security posture.

https://github.com/treestryder/powershell_module_workdayapi/wiki/SSL-and-TLS-1.0

**Comment by treestryder** [comment]
Oh, and, sorry about the install script. I am likely to remove it, now that the module is hosted on the Powershell Gallery. Now to install, use:

`Install-Module WorkdayAPI`

The -Scope parameter can be used to install to the user's profile.

**Comment by emanent** [comment]
for our last connection issue we had to add an explicit call to proxy in addition to the Tls12 enforcing and it worked..

$wc=New-Object System.Net.Webclient
$wc.Proxy.Credentials=[System.Net.CredentialCache]::DefaultNetworkCredentialsls
