### ISSUE TITLE
need to parameteryze DeviceType in Set-WorkdayWorkerPhone

### ISSUE THREAD

**Issue by emanent** [treestryder/powershell_module_workdayapi#14]
Hello all
as we use a european based WD, we don't have the  DeviceType='Landline'
instead we do have a DeviceType='WORK' in our configuration
but the most important is that it can be different from the hard-coded one so the best approach should be to set it as a parameter (with a possible defaultvalue set to 'Landline' so we don't break existing scripts).
i can derive a function from yours for my usage but it may be interesting to add this to the official package ?
regards
Emmanuel

**Comment by emanent** [comment]
it looks like the same issue loged here 
https://dereksysadmin.wordpress.com/2018/05/17/workday-powershell/

**Comment by treestryder** [comment]
Thanks for reminding me, I had intended to fix that problem long ago. I've removed the set validation. Folks will just have to know what their system uses.
