### ISSUE TITLE
Does this API support API version 34.2 auth model?

### ISSUE THREAD

**Issue by seattlekyle** [treestryder/powershell_module_workdayapi#21]
I am doing this and getting invalid username or password...

Import-Module WorkdayApi

$username = 'testuser@company'
$password = ConvertTo-SecureString 'Workday2020' -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ($username, $password)

Set-WorkdayCredential -Credential $credential
Set-WorkdayEndpoint -Endpoint Human_Resources -Uri 'https://wd5-impl-services1.workday.com/ccx/service/company/Human_Resources/v34.2'
Save-WorkdayConfiguration

Get-WorkdayWorkerPhoto -WorkerId 89175 -WorkerType Employee_ID -Path 'C:\Users\kyle.burmark\Desktop\workday'

**Comment by treestryder** [comment]
Hopefully Workday hasn't changed how their authentication works, this would break all of the calls. Each call has its own version it was written for specified and the authentication is outside of this.

Could it be that the account still needs some configuration?
See the notes in [Issue #6](https://github.com/treestryder/powershell_module_workdayapi/issues/6).

Does Get-WorkdayDate work?

**Comment by seattlekyle** [comment]
I tested it and it works. Our HR lady just set up the username wrong for me but we resolved issue. Works in 34.2 api.
