### ISSUE TITLE
Get-WorkdayWorker Active property is blank

### ISSUE THREAD

**Issue by Skatterbrainz** [treestryder/powershell_module_workdayapi#25]
The results I get back from Get-WorkdayWorker, with or without -WorkerId being used, return WorkerWid, WorkerDescriptor, WorkerType, WorkerId, and XML. The other properties are always blank, including Active.  Is this by design and is there another function or parameter to request the Active property on each user?

**Comment by treestryder** [comment]
The " -IncludeWork" switch parameter is needed. Other things require "-IncludePersonal". This is both an artifact of the Workday API, and an attempt to make things faster and lighter weight.

**Comment by Skatterbrainz** [comment]
I found out the issue was permissions assigned in the API, not an issue with your module or code. Thank you!
