### ISSUE TITLE
Get-WorkdayWorker -WorkerType is ignored

### ISSUE THREAD

**Issue by Skatterbrainz** [treestryder/powershell_module_workdayapi#26]
When using Get-WorkdayWorker with -WorkerType Contingent_Worker_ID or Employee_ID, it always returns the same data, which are all workers combined.

**Comment by treestryder** [comment]
Without a Worker ID specified Get-WorkdayWorker returns all workers.

**Comment by Skatterbrainz** [comment]
No worries. Thank you!
