### ISSUE TITLE
CWR and Employees?

### ISSUE THREAD

**Issue by mtengmo** [treestryder/powershell_module_workdayapi#28]
It´s looks like the module doesn´t take CWR into the scope?

**Comment by treestryder** [comment]
By CWR, do you mean Contingent Worker? If so, it is specified using the WorkerType parameter on many functions and is returned 
 by many functions under the same name.

Examples
* [Get-WorkdayWorker.ps1](https://github.com/treestryder/powershell_module_workdayapi/blob/master/source/public/Get-WorkdayWorker.ps1)
* [ConvertFrom-WorkdayWorkerXml.ps1](https://github.com/treestryder/powershell_module_workdayapi/blob/f3a450be224a273f8f48908626fc57d15aa030c8/source/public/ConvertFrom-WorkdayWorkerXml.ps1#L57C24-L57C24)
