### ISSUE TITLE
Cross Platform

### ISSUE THREAD

**Issue by BarnumD** [treestryder/powershell_module_workdayapi#3]
I'm running this in Powershell core 6.0 on Ubuntu.  Some of the parameters are hard coded for a Windows environment.  Some I can provide as parameter at install, others I could not control.

**Comment by BarnumD** [comment]
The above mentioned pull request allowed me to install on powershell core on Ubuntu (actually in a docker container) and allowed me to at the very least attempt to run `Get-WorkdayReport`.  I'm not sure if this will fix all cross-platform issues or not.

**Comment by treestryder** [comment]
I like this idea, very much, and will try to keep cross-platform support in mind. However, I do not have the time to support anything beyond the needs of my company and thus, will not be able to test in a non-Windows Powershell v5 environment.

**Comment by treestryder** [comment]
With installation now through the Powershell Gallery and recently melding the location of the configuration file to the root of the user's profile, I believe all cross-platform issues have been resolved. For now.
