### ISSUE TITLE
Add/clarify license

### ISSUE THREAD

**Issue by cosmocracy** [treestryder/powershell_module_workdayapi#36]
Your project looks fantastic. I'm tempted to use it to get a jump-start on some integrations for my employer.  If your intent is for this to be freely-usable, would you consider adding a license to the project to clarify?  Thank you and again, great project!

https://opensource.org/licenses/

**Comment by treestryder** [comment]
There is one, hidden a directory deep.
https://github.com/treestryder/powershell_module_workdayapi/blob/master/source/License.txt

Please note, I currently have no time to work on this project and am looking for help. See issue #7 .
