### ISSUE TITLE
PowerShell Gallery - Package Unlisted

### ISSUE THREAD

**Issue by YuriySamorodov** [treestryder/powershell_module_workdayapi#42]
Hi,

Just noticed WorkDayAPI 2.3.2 package is marked as unlisted on https://www.powershellgallery.com/packages/WorkdayApi/2.3.2:
<img width="785" alt="CleanShot 2024-03-29 at 16 06 18" src="https://github.com/treestryder/powershell_module_workdayapi/assets/5260172/8d294066-187d-4abf-847c-ff1a0aa7b820">
```Find-Module WorkdayApi``` returns the following error as well:

> PackageManagement\Find-Package : No match was found for the specified search criteria and module name
> 'WorkdayApi'. Try Get-PSRepository to see all available registered module repositories

![CleanShot 2024-03-29 at 16 10 44](https://github.com/treestryder/powershell_module_workdayapi/assets/5260172/babe041d-058f-42c9-b99b-d44db0e46259)

Is there any issues preventing WorkdayApi module from being published?

**Comment by treestryder** [comment]
Sorry. I have been considering quitting this project for a long time. I just do not have the time, energy, nor access to a Workday test environment, to work on it. This is why I created issue #7 . After a couple of hours wrestling with Powershell Get / Gallery bugs that blocked my ability to update the gallery package, I finally gave up. Unlisting the package was a quick first step. Next I need to deal with this GitHub project... As it is, I am typing this when I should be walking out the door.
